;;; minmacs-inf.el --- automatically extracted builtin package list
;;
;;; Code:

(setq minmacs-packages
      '((5x5 "play/5x5.el")
	(ada-mode "progmodes/ada-mode.el" "progmodes/ada-prj.el" "progmodes/ada-stmt.el" "progmodes/ada-xref.el")
	(add-log "vc/add-log.el")
	(align "align.el")
	(allout "allout.el")
	(allout-widgets "allout-widgets.el")
	(ange-ftp "net/ange-ftp.el")
	(animate "play/animate.el")
	(ansi-color "ansi-color.el")
	(antlr-mode "progmodes/antlr-mode.el")
	(arc-mode "arc-mode.el")
	(array "array.el")
	(artist "textmodes/artist.el")
	(asm-mode "progmodes/asm-mode.el")
	(assoc "emacs-lisp/assoc.el")
	(autoarg "autoarg.el")
	(autoconf "progmodes/autoconf.el")
	(autoinsert "autoinsert.el")
	(autorevert "autorevert.el")
	(avl-tree "emacs-lisp/avl-tree.el")
	(avoid "avoid.el")
	(battery "battery.el")
	(benchmark "emacs-lisp/benchmark.el")
	(bib-mode "textmodes/bib-mode.el")
	(bibtex "textmodes/bibtex.el")
	(bibtex-style "textmodes/bibtex-style.el")
	(bindat "emacs-lisp/bindat.el")
	(binhex "mail/binhex.el")
	(blackbox "play/blackbox.el")
	(bookmark "bookmark.el")
	(browse-url "net/browse-url.el")
	(bruce "play/bruce.el")
	(bs "bs.el")
	(bubbles "play/bubbles.el")
	(bug-reference "progmodes/bug-reference.el")
	(calc "calc/README" "calc/README.prev" "calc/calc-aent.el" "calc/calc-alg.el" "calc/calc-arith.el" "calc/calc-bin.el" "calc/calc-comb.el" "calc/calc-cplx.el" "calc/calc-embed.el" "calc/calc-ext.el" "calc/calc-fin.el" "calc/calc-forms.el" "calc/calc-frac.el" "calc/calc-funcs.el" "calc/calc-graph.el" "calc/calc-help.el" "calc/calc-incom.el" "calc/calc-keypd.el" "calc/calc-lang.el" "calc/calc-macs.el" "calc/calc-map.el" "calc/calc-math.el" "calc/calc-menu.el" "calc/calc-misc.el" "calc/calc-mode.el" "calc/calc-mtx.el" "calc/calc-nlfit.el" "calc/calc-poly.el" "calc/calc-prog.el" "calc/calc-rewr.el" "calc/calc-rules.el" "calc/calc-sel.el" "calc/calc-stat.el" "calc/calc-store.el" "calc/calc-stuff.el" "calc/calc-trail.el" "calc/calc-undo.el" "calc/calc-units.el" "calc/calc-vec.el" "calc/calc-yank.el" "calc/calc.el" "calc/calcalg2.el" "calc/calcalg3.el" "calc/calccomp.el" "calc/calcsel2.el")
	(calculator "calculator.el")
	(calendar "calendar/appt.el" "calendar/cal-bahai.el" "calendar/cal-china.el" "calendar/cal-coptic.el" "calendar/cal-dst.el" "calendar/cal-french.el" "calendar/cal-hebrew.el" "calendar/cal-html.el" "calendar/cal-islam.el" "calendar/cal-iso.el" "calendar/cal-julian.el" "calendar/cal-mayan.el" "calendar/cal-menu.el" "calendar/cal-move.el" "calendar/cal-persia.el" "calendar/cal-tex.el" "calendar/cal-x.el" "calendar/calendar.el" "calendar/holidays.el" "calendar/lunar.el" "calendar/solar.el")
	(cap-words "progmodes/cap-words.el")
	(cc-guess "progmodes/cc-guess.el")
	(cc-mode "progmodes/cc-align.el" "progmodes/cc-awk.el" "progmodes/cc-bytecomp.el" "progmodes/cc-cmds.el" "progmodes/cc-compat.el" "progmodes/cc-defs.el" "progmodes/cc-engine.el" "progmodes/cc-fonts.el" "progmodes/cc-langs.el" "progmodes/cc-menus.el" "progmodes/cc-mode.el" "progmodes/cc-styles.el" "progmodes/cc-vars.el")
	(cdl "cdl.el")
	(cedet "cedet/ChangeLog" "cedet/cedet-cscope.el" "cedet/cedet-files.el" "cedet/cedet-global.el" "cedet/cedet-idutils.el" "cedet/cedet.el" "cedet/data-debug.el" "cedet/ede" "cedet/ede.el" "cedet/ede/auto.el" "cedet/ede/autoconf-edit.el" "cedet/ede/base.el" "cedet/ede/cpp-root.el" "cedet/ede/custom.el" "cedet/ede/dired.el" "cedet/ede/emacs.el" "cedet/ede/files.el" "cedet/ede/generic.el" "cedet/ede/linux.el" "cedet/ede/locate.el" "cedet/ede/make.el" "cedet/ede/makefile-edit.el" "cedet/ede/pconf.el" "cedet/ede/pmake.el" "cedet/ede/proj-archive.el" "cedet/ede/proj-aux.el" "cedet/ede/proj-comp.el" "cedet/ede/proj-elisp.el" "cedet/ede/proj-info.el" "cedet/ede/proj-misc.el" "cedet/ede/proj-obj.el" "cedet/ede/proj-prog.el" "cedet/ede/proj-scheme.el" "cedet/ede/proj-shared.el" "cedet/ede/proj.el" "cedet/ede/project-am.el" "cedet/ede/shell.el" "cedet/ede/simple.el" "cedet/ede/source.el" "cedet/ede/speedbar.el" "cedet/ede/srecode.el" "cedet/ede/system.el" "cedet/ede/util.el" "cedet/inversion.el" "cedet/mode-local.el" "cedet/pulse.el" "cedet/semantic" "cedet/semantic.el" "cedet/semantic/analyze" "cedet/semantic/analyze.el" "cedet/semantic/analyze/complete.el" "cedet/semantic/analyze/debug.el" "cedet/semantic/analyze/fcn.el" "cedet/semantic/analyze/refs.el" "cedet/semantic/bovine" "cedet/semantic/bovine.el" "cedet/semantic/bovine/c-by.el" "cedet/semantic/bovine/c.el" "cedet/semantic/bovine/debug.el" "cedet/semantic/bovine/el.el" "cedet/semantic/bovine/gcc.el" "cedet/semantic/bovine/make-by.el" "cedet/semantic/bovine/make.el" "cedet/semantic/bovine/scm-by.el" "cedet/semantic/bovine/scm.el" "cedet/semantic/chart.el" "cedet/semantic/complete.el" "cedet/semantic/ctxt.el" "cedet/semantic/db-debug.el" "cedet/semantic/db-ebrowse.el" "cedet/semantic/db-el.el" "cedet/semantic/db-file.el" "cedet/semantic/db-find.el" "cedet/semantic/db-global.el" "cedet/semantic/db-javascript.el" "cedet/semantic/db-mode.el" "cedet/semantic/db-ref.el" "cedet/semantic/db-typecache.el" "cedet/semantic/db.el" "cedet/semantic/debug.el" "cedet/semantic/decorate" "cedet/semantic/decorate.el" "cedet/semantic/decorate/include.el" "cedet/semantic/decorate/mode.el" "cedet/semantic/dep.el" "cedet/semantic/doc.el" "cedet/semantic/ede-grammar.el" "cedet/semantic/edit.el" "cedet/semantic/find.el" "cedet/semantic/format.el" "cedet/semantic/fw.el" "cedet/semantic/grammar-wy.el" "cedet/semantic/grammar.el" "cedet/semantic/html.el" "cedet/semantic/ia-sb.el" "cedet/semantic/ia.el" "cedet/semantic/idle.el" "cedet/semantic/imenu.el" "cedet/semantic/java.el" "cedet/semantic/lex-spp.el" "cedet/semantic/lex.el" "cedet/semantic/mru-bookmark.el" "cedet/semantic/sb.el" "cedet/semantic/scope.el" "cedet/semantic/senator.el" "cedet/semantic/sort.el" "cedet/semantic/symref" "cedet/semantic/symref.el" "cedet/semantic/symref/cscope.el" "cedet/semantic/symref/filter.el" "cedet/semantic/symref/global.el" "cedet/semantic/symref/grep.el" "cedet/semantic/symref/idutils.el" "cedet/semantic/symref/list.el" "cedet/semantic/tag-file.el" "cedet/semantic/tag-ls.el" "cedet/semantic/tag-write.el" "cedet/semantic/tag.el" "cedet/semantic/texi.el" "cedet/semantic/util-modes.el" "cedet/semantic/util.el" "cedet/semantic/wisent" "cedet/semantic/wisent.el" "cedet/semantic/wisent/comp.el" "cedet/semantic/wisent/java-tags.el" "cedet/semantic/wisent/javascript.el" "cedet/semantic/wisent/javat-wy.el" "cedet/semantic/wisent/js-wy.el" "cedet/semantic/wisent/python-wy.el" "cedet/semantic/wisent/python.el" "cedet/semantic/wisent/wisent.el" "cedet/srecode" "cedet/srecode.el" "cedet/srecode/args.el" "cedet/srecode/compile.el" "cedet/srecode/cpp.el" "cedet/srecode/ctxt.el" "cedet/srecode/dictionary.el" "cedet/srecode/document.el" "cedet/srecode/el.el" "cedet/srecode/expandproto.el" "cedet/srecode/extract.el" "cedet/srecode/fields.el" "cedet/srecode/filters.el" "cedet/srecode/find.el" "cedet/srecode/getset.el" "cedet/srecode/insert.el" "cedet/srecode/java.el" "cedet/srecode/map.el" "cedet/srecode/mode.el" "cedet/srecode/semantic.el" "cedet/srecode/srt-mode.el" "cedet/srecode/srt-wy.el" "cedet/srecode/srt.el" "cedet/srecode/table.el" "cedet/srecode/template.el" "cedet/srecode/texi.el")
	(cfengine "progmodes/cfengine.el")
	(chart "emacs-lisp/chart.el")
	(check-declare "emacs-lisp/check-declare.el")
	(checkdoc "emacs-lisp/checkdoc.el")
	(chistory "chistory.el")
	(cl "emacs-lisp/cl-loaddefs.el" "emacs-lisp/cl.el")
	(cmacexp "progmodes/cmacexp.el")
	(cmuscheme "cmuscheme.el")
	(color "color.el")
	(compare-w "vc/compare-w.el")
	(compile "progmodes/compile.el")
	(completion "completion.el")
	(conf-mode "textmodes/conf-mode.el")
	(cookie1 "play/cookie1.el")
	(copyright "emacs-lisp/copyright.el")
	(cperl-mode "progmodes/cperl-mode.el")
	(cpp "progmodes/cpp.el")
	(crisp "emulation/crisp.el")
	(crm "emacs-lisp/crm.el")
	(css-mode "textmodes/css-mode.el")
	(cua-base "emulation/cua-base.el" "emulation/cua-gmrk.el" "emulation/cua-rect.el")
	(cust-print "emacs-lisp/cust-print.el")
	(cvs-status "vc/cvs-status.el")
	(cwarn "progmodes/cwarn.el")
	(dabbrev "dabbrev.el")
	(dbus "net/dbus.el")
	(dcl-mode "progmodes/dcl-mode.el")
	(debug "emacs-lisp/debug.el")
	(decipher "play/decipher.el")
	(delim-col "delim-col.el")
	(delphi "progmodes/delphi.el")
	(delsel "delsel.el")
	(descr-text "descr-text.el")
	(desktop "desktop.el")
	(dframe "dframe.el")
	(diary-lib "calendar/diary-lib.el")
	(diff "vc/diff.el")
	(diff-mode "vc/diff-mode.el")
	(dig "net/dig.el")
	(dirtrack "dirtrack.el")
	(disass "emacs-lisp/disass.el")
	(dissociate "play/dissociate.el")
	(dns "net/dns.el")
	(dns-mode "textmodes/dns-mode.el")
	(doc-view "doc-view.el")
	(doctor "play/doctor.el")
	(double "double.el")
	(dunnet "play/dunnet.el")
	(ebnf2ps "progmodes/ebnf-abn.el" "progmodes/ebnf-bnf.el" "progmodes/ebnf-dtd.el" "progmodes/ebnf-ebx.el" "progmodes/ebnf-iso.el" "progmodes/ebnf-otz.el" "progmodes/ebnf-yac.el" "progmodes/ebnf2ps.el")
	(ebrowse "progmodes/ebrowse.el")
	(ebuff-menu "ebuff-menu.el")
	(echistory "echistory.el")
	(edebug "emacs-lisp/edebug.el")
	(ediff "vc/ediff-diff.el" "vc/ediff-help.el" "vc/ediff-hook.el" "vc/ediff-init.el" "vc/ediff-merg.el" "vc/ediff-mult.el" "vc/ediff-ptch.el" "vc/ediff-util.el" "vc/ediff-vers.el" "vc/ediff-wind.el" "vc/ediff.el")
	(edmacro "edmacro.el")
	(edt "emulation/edt-lk201.el" "emulation/edt-mapper.el" "emulation/edt-pc.el" "emulation/edt-vt100.el" "emulation/edt.el")
	(ehelp "ehelp.el")
	(eieio "emacs-lisp/eieio-base.el" "emacs-lisp/eieio-custom.el" "emacs-lisp/eieio-datadebug.el" "emacs-lisp/eieio-opt.el" "emacs-lisp/eieio-speedbar.el" "emacs-lisp/eieio.el")
	(eldoc "emacs-lisp/eldoc.el")
	(electric "electric.el")
	(elide-head "elide-head.el")
	(elint "emacs-lisp/elint.el")
	(elp "emacs-lisp/elp.el")
	(emacs "abbrev.el" "apropos.el" "bindings.el" "buff-menu.el" "button.el" "case-table.el" "comint.el" "composite.el" "cus-dep.el" "cus-edit.el" "cus-face.el" "cus-start.el" "cus-theme.el" "custom.el" "dired-aux.el" "dired-x.el" "dired.el" "disp-table.el" "dnd.el" "dos-fns.el" "dos-vars.el" "dos-w32.el" "dynamic-setting.el" "emacs-lisp/advice.el" "emacs-lisp/authors.el" "emacs-lisp/autoload.el" "emacs-lisp/backquote.el" "emacs-lisp/byte-opt.el" "emacs-lisp/byte-run.el" "emacs-lisp/bytecomp.el" "emacs-lisp/cconv.el" "emacs-lisp/cl-extra.el" "emacs-lisp/cl-indent.el" "emacs-lisp/cl-macs.el" "emacs-lisp/cl-seq.el" "emacs-lisp/cl-specs.el" "emacs-lisp/derived.el" "emacs-lisp/easy-mmode.el" "emacs-lisp/easymenu.el" "emacs-lisp/float-sup.el" "emacs-lisp/generic.el" "emacs-lisp/helper.el" "emacs-lisp/lisp-mode.el" "emacs-lisp/lisp.el" "emacs-lisp/timer.el" "env.el" "epa-hook.el" "facemenu.el" "faces.el" "files-x.el" "files.el" "font-core.el" "font-lock.el" "format.el" "frame.el" "fringe.el" "generic-x.el" "help-fns.el" "help-macro.el" "help-mode.el" "help.el" "image-mode.el" "image.el" "indent.el" "international/README" "international/ccl.el" "international/characters.el" "international/charprop.el" "international/cp51932.el" "international/eucjp-ms.el" "international/fontset.el" "international/isearch-x.el" "international/iso-ascii.el" "international/iso-cvt.el" "international/iso-transl.el" "international/ja-dic-cnv.el" "international/ja-dic-utl.el" "international/kinsoku.el" "international/kkc.el" "international/latexenc.el" "international/latin1-disp.el" "international/mule-cmds.el" "international/mule-conf.el" "international/mule-diag.el" "international/mule-util.el" "international/mule.el" "international/ogonek.el" "international/quail.el" "international/robin.el" "international/titdic-cnv.el" "international/ucs-normalize.el" "international/uni-bidi.el" "international/uni-category.el" "international/uni-combining.el" "international/uni-comment.el" "international/uni-decimal.el" "international/uni-decomposition.el" "international/uni-digit.el" "international/uni-lowercase.el" "international/uni-mirrored.el" "international/uni-name.el" "international/uni-numeric.el" "international/uni-old-name.el" "international/uni-titlecase.el" "international/uni-uppercase.el" "international/utf-7.el" "isearch.el" "jit-lock.el" "jka-cmpr-hook.el" "language/burmese.el" "language/cham.el" "language/china-util.el" "language/chinese.el" "language/cyril-util.el" "language/cyrillic.el" "language/czech.el" "language/english.el" "language/ethio-util.el" "language/ethiopic.el" "language/european.el" "language/georgian.el" "language/greek.el" "language/hanja-util.el" "language/hebrew.el" "language/ind-util.el" "language/indian.el" "language/japan-util.el" "language/japanese.el" "language/khmer.el" "language/korea-util.el" "language/korean.el" "language/lao-util.el" "language/lao.el" "language/misc-lang.el" "language/romanian.el" "language/sinhala.el" "language/slovak.el" "language/tai-viet.el" "language/thai-util.el" "language/thai-word.el" "language/thai.el" "language/tibet-util.el" "language/tibetan.el" "language/tv-util.el" "language/utf-8-lang.el" "language/viet-util.el" "language/vietnamese.el" "loadup.el" "ls-lisp.el" "macros.el" "mail/blessmail.el" "mail/emacsbug.el" "menu-bar.el" "minibuffer.el" "misc.el" "mouse.el" "mwheel.el" "newcomment.el" "obsolete/abbrevlist.el" "obsolete/awk-mode.el" "obsolete/cl-compat.el" "obsolete/complete.el" "obsolete/erc-hecomplete.el" "obsolete/fast-lock.el" "obsolete/iso-acc.el" "obsolete/iso-insert.el" "obsolete/iso-swed.el" "obsolete/keyswap.el" "obsolete/lazy-lock.el" "obsolete/levents.el" "obsolete/lmenu.el" "obsolete/lucid.el" "obsolete/old-emacs-lock.el" "obsolete/old-whitespace.el" "obsolete/options.el" "obsolete/pc-mode.el" "obsolete/pc-select.el" "obsolete/pgg-def.el" "obsolete/pgg-gpg.el" "obsolete/pgg-parse.el" "obsolete/pgg-pgp.el" "obsolete/pgg-pgp5.el" "obsolete/pgg.el" "obsolete/resume.el" "obsolete/s-region.el" "obsolete/scribe.el" "obsolete/spell.el" "obsolete/sregex.el" "obsolete/swedish.el" "obsolete/sym-comp.el" "obsolete/vc-mcvs.el" "paths.el" "rect.el" "register.el" "replace.el" "rfn-eshadow.el" "scroll-bar.el" "simple.el" "startup.el" "subr.el" "tabify.el" "term/AT386.el" "term/README" "term/apollo.el" "term/bobcat.el" "term/common-win.el" "term/cygwin.el" "term/internal.el" "term/iris-ansi.el" "term/linux.el" "term/lk201.el" "term/news.el" "term/ns-win.el" "term/pc-win.el" "term/rxvt.el" "term/screen.el" "term/sun.el" "term/sup-mouse.el" "term/tty-colors.el" "term/tvi970.el" "term/vt100.el" "term/vt102.el" "term/vt125.el" "term/vt200.el" "term/vt201.el" "term/vt220.el" "term/vt240.el" "term/vt300.el" "term/vt320.el" "term/vt400.el" "term/vt420.el" "term/w32-win.el" "term/w32console.el" "term/wyse50.el" "term/x-win.el" "term/xterm.el" "textmodes/fill.el" "textmodes/page.el" "textmodes/paragraphs.el" "textmodes/text-mode.el" "tool-bar.el" "tooltip.el" "tutorial.el" "uniquify.el" "version.el" "w32-fns.el" "w32-vars.el" "wid-browse.el" "wid-edit.el" "widget.el" "window.el" "x-dnd.el")
	(emacs-lock "emacs-lock.el")
	(emerge "vc/emerge.el")
	(enriched "textmodes/enriched.el")
	(epa "epa-dired.el" "epa-file.el" "epa-mail.el" "epa.el")
	(epg "epg-config.el" "epg.el")
	(erc "erc/ChangeLog" "erc/ChangeLog.01" "erc/ChangeLog.02" "erc/ChangeLog.03" "erc/ChangeLog.04" "erc/ChangeLog.05" "erc/ChangeLog.06" "erc/ChangeLog.07" "erc/ChangeLog.08" "erc/erc-autoaway.el" "erc/erc-backend.el" "erc/erc-button.el" "erc/erc-capab.el" "erc/erc-compat.el" "erc/erc-dcc.el" "erc/erc-ezbounce.el" "erc/erc-fill.el" "erc/erc-goodies.el" "erc/erc-ibuffer.el" "erc/erc-identd.el" "erc/erc-imenu.el" "erc/erc-join.el" "erc/erc-lang.el" "erc/erc-list.el" "erc/erc-log.el" "erc/erc-match.el" "erc/erc-menu.el" "erc/erc-netsplit.el" "erc/erc-networks.el" "erc/erc-notify.el" "erc/erc-page.el" "erc/erc-pcomplete.el" "erc/erc-replace.el" "erc/erc-ring.el" "erc/erc-services.el" "erc/erc-sound.el" "erc/erc-speedbar.el" "erc/erc-spelling.el" "erc/erc-stamp.el" "erc/erc-track.el" "erc/erc-truncate.el" "erc/erc-xdcc.el" "erc/erc.el")
	(ert "emacs-lisp/ert.el")
	(ert-x "emacs-lisp/ert-x.el")
	(eshell "eshell/em-alias.el" "eshell/em-banner.el" "eshell/em-basic.el" "eshell/em-cmpl.el" "eshell/em-dirs.el" "eshell/em-glob.el" "eshell/em-hist.el" "eshell/em-ls.el" "eshell/em-pred.el" "eshell/em-prompt.el" "eshell/em-rebind.el" "eshell/em-script.el" "eshell/em-smart.el" "eshell/em-term.el" "eshell/em-unix.el" "eshell/em-xtra.el" "eshell/esh-arg.el" "eshell/esh-cmd.el" "eshell/esh-ext.el" "eshell/esh-io.el" "eshell/esh-mode.el" "eshell/esh-module.el" "eshell/esh-opt.el" "eshell/esh-proc.el" "eshell/esh-util.el" "eshell/esh-var.el" "eshell/eshell.el")
	(etags "progmodes/etags.el")
	(eudc "net/eudc-bob.el" "net/eudc-export.el" "net/eudc-hotlist.el" "net/eudc-vars.el" "net/eudc.el" "net/eudcb-bbdb.el" "net/eudcb-ldap.el" "net/eudcb-mab.el" "net/eudcb-ph.el")
	(ewoc "emacs-lisp/ewoc.el")
	(executable "progmodes/executable.el")
	(expand "expand.el")
	(ezimage "ezimage.el")
	(f90 "progmodes/f90.el")
	(face-remap "face-remap.el")
	(feedmail "mail/feedmail.el")
	(ffap "ffap.el")
	(filecache "filecache.el")
	(filesets "filesets.el")
	(find-cmd "find-cmd.el")
	(find-dired "find-dired.el")
	(find-file "find-file.el")
	(find-func "emacs-lisp/find-func.el")
	(find-gc "emacs-lisp/find-gc.el")
	(find-lisp "find-lisp.el")
	(finder "finder.el")
	(flow-ctrl "flow-ctrl.el")
	(flymake "progmodes/flymake.el")
	(flyspell "textmodes/flyspell.el")
	(foldout "foldout.el")
	(follow "follow.el")
	(footnote "mail/footnote.el")
	(format-spec "format-spec.el")
	(forms "forms.el")
	(forms-d2 "forms-d2.el")
	(forms-pass "forms-pass.el")
	(fortran "progmodes/fortran.el")
	(fortune "play/fortune.el")
	(gamegrid "play/gamegrid.el")
	(gametree "play/gametree.el")
	(gdb-mi "progmodes/gdb-mi.el")
	(glasses "progmodes/glasses.el")
	(gnus "gnus/ChangeLog" "gnus/ChangeLog.1" "gnus/ChangeLog.2" "gnus/auth-source.el" "gnus/canlock.el" "gnus/compface.el" "gnus/deuglify.el" "gnus/ecomplete.el" "gnus/flow-fill.el" "gnus/gmm-utils.el" "gnus/gnus-agent.el" "gnus/gnus-art.el" "gnus/gnus-async.el" "gnus/gnus-bcklg.el" "gnus/gnus-bookmark.el" "gnus/gnus-cache.el" "gnus/gnus-cite.el" "gnus/gnus-cus.el" "gnus/gnus-delay.el" "gnus/gnus-demon.el" "gnus/gnus-diary.el" "gnus/gnus-dired.el" "gnus/gnus-draft.el" "gnus/gnus-dup.el" "gnus/gnus-eform.el" "gnus/gnus-ems.el" "gnus/gnus-fun.el" "gnus/gnus-gravatar.el" "gnus/gnus-group.el" "gnus/gnus-html.el" "gnus/gnus-int.el" "gnus/gnus-kill.el" "gnus/gnus-logic.el" "gnus/gnus-mh.el" "gnus/gnus-ml.el" "gnus/gnus-mlspl.el" "gnus/gnus-msg.el" "gnus/gnus-picon.el" "gnus/gnus-range.el" "gnus/gnus-registry.el" "gnus/gnus-salt.el" "gnus/gnus-score.el" "gnus/gnus-setup.el" "gnus/gnus-sieve.el" "gnus/gnus-spec.el" "gnus/gnus-srvr.el" "gnus/gnus-start.el" "gnus/gnus-sum.el" "gnus/gnus-sync.el" "gnus/gnus-topic.el" "gnus/gnus-undo.el" "gnus/gnus-util.el" "gnus/gnus-uu.el" "gnus/gnus-vm.el" "gnus/gnus-win.el" "gnus/gnus.el" "gnus/gravatar.el" "gnus/gssapi.el" "gnus/html2text.el" "gnus/ietf-drums.el" "gnus/legacy-gnus-agent.el" "gnus/mail-parse.el" "gnus/mail-prsvr.el" "gnus/mail-source.el" "gnus/mailcap.el" "gnus/message.el" "gnus/messcompat.el" "gnus/mm-bodies.el" "gnus/mm-decode.el" "gnus/mm-encode.el" "gnus/mm-extern.el" "gnus/mm-partial.el" "gnus/mm-url.el" "gnus/mm-util.el" "gnus/mm-uu.el" "gnus/mm-view.el" "gnus/mml-sec.el" "gnus/mml-smime.el" "gnus/mml.el" "gnus/mml1991.el" "gnus/mml2015.el" "gnus/nnagent.el" "gnus/nnbabyl.el" "gnus/nndiary.el" "gnus/nndir.el" "gnus/nndoc.el" "gnus/nndraft.el" "gnus/nneething.el" "gnus/nnfolder.el" "gnus/nngateway.el" "gnus/nnheader.el" "gnus/nnimap.el" "gnus/nnir.el" "gnus/nnmail.el" "gnus/nnmaildir.el" "gnus/nnmairix.el" "gnus/nnmbox.el" "gnus/nnmh.el" "gnus/nnml.el" "gnus/nnnil.el" "gnus/nnoo.el" "gnus/nnregistry.el" "gnus/nnrss.el" "gnus/nnspool.el" "gnus/nntp.el" "gnus/nnvirtual.el" "gnus/nnweb.el" "gnus/plstore.el" "gnus/pop3.el" "gnus/qp.el" "gnus/registry.el" "gnus/rfc1843.el" "gnus/rfc2045.el" "gnus/rfc2047.el" "gnus/rfc2104.el" "gnus/rfc2231.el" "gnus/rtree.el" "gnus/score-mode.el" "gnus/shr-color.el" "gnus/shr.el" "gnus/sieve-manage.el" "gnus/sieve-mode.el" "gnus/sieve.el" "gnus/smiley.el" "gnus/smime.el" "gnus/spam-report.el" "gnus/spam-stat.el" "gnus/spam-wash.el" "gnus/spam.el" "gnus/starttls.el" "gnus/utf7.el" "gnus/yenc.el")
	(gnutls "net/gnutls.el")
	(gomoku "play/gomoku.el")
	(goto-addr "net/goto-addr.el")
	(grep "progmodes/grep.el")
	(gs "gs.el")
	(gud "progmodes/gud.el")
	(gulp "emacs-lisp/gulp.el")
	(handwrite "play/handwrite.el")
	(hanoi "play/hanoi.el")
	(hashcash "mail/hashcash.el")
	(help-at-pt "help-at-pt.el")
	(hex-util "hex-util.el")
	(hexl "hexl.el")
	(hi-lock "hi-lock.el")
	(hideif "progmodes/hideif.el")
	(hideshow "progmodes/hideshow.el")
	(hilit-chg "hilit-chg.el")
	(hippie-exp "hippie-exp.el")
	(hl-line "hl-line.el")
	(hmac-def "net/hmac-def.el")
	(hmac-md5 "net/hmac-md5.el")
	(htmlfontify "hfy-cmap.el" "htmlfontify.el")
	(ibuffer "ibuf-ext.el" "ibuf-macs.el" "ibuffer.el")
	(icalendar "calendar/icalendar.el")
	(icomplete "icomplete.el")
	(icon "progmodes/icon.el")
	(idlwave "progmodes/idlw-complete-structtag.el" "progmodes/idlw-help.el" "progmodes/idlw-shell.el" "progmodes/idlw-toolbar.el" "progmodes/idlwave.el")
	(ido "ido.el")
	(ielm "ielm.el")
	(iimage "iimage.el")
	(image-dired "image-dired.el")
	(image-file "image-file.el")
	(imap "net/imap.el")
	(imenu "imenu.el")
	(inf-lisp "progmodes/inf-lisp.el")
	(info "info.el")
	(info-look "info-look.el")
	(info-xref "info-xref.el")
	(informat "informat.el")
	(isearchb "isearchb.el")
	(ispell "textmodes/ispell.el")
	(iswitchb "iswitchb.el")
	(jka-compr "jka-compr.el")
	(js "progmodes/js.el")
	(json "json.el")
	(kermit "kermit.el")
	(keypad "emulation/keypad.el")
	(kmacro "kmacro.el")
	(landmark "play/landmark.el")
	(ld-script "progmodes/ld-script.el")
	(ldap "net/ldap.el")
	(ledit "ledit.el")
	(life "play/life.el")
	(linum "linum.el")
	(lisp-mnt "emacs-lisp/lisp-mnt.el")
	(loadhist "loadhist.el")
	(locate "locate.el")
	(log-edit "vc/log-edit.el")
	(log-view "vc/log-view.el")
	(longlines "longlines.el")
	(lpr "lpr.el")
	(m4-mode "progmodes/m4-mode.el")
	(macroexp "emacs-lisp/macroexp.el")
	(mail-utils "mail/mail-extr.el" "mail/mail-hist.el" "mail/mail-utils.el" "mail/mailheader.el")
	(mailabbrev "mail/mailabbrev.el")
	(mailalias "mail/mailalias.el")
	(mailclient "mail/mailclient.el")
	(mailpost "mail/mailpost.el")
	(mairix "net/mairix.el")
	(make-mode "progmodes/make-mode.el")
	(makeinfo "textmodes/makeinfo.el")
	(makesum "makesum.el")
	(man "man.el")
	(mantemp "progmodes/mantemp.el")
	(map-ynp "emacs-lisp/map-ynp.el")
	(master "master.el")
	(mb-depth "mb-depth.el")
	(md4 "md4.el")
	(meese "play/meese.el")
	(meta-mode "progmodes/meta-mode.el")
	(metamail "mail/metamail.el")
	(mh-e "mh-e/ChangeLog" "mh-e/ChangeLog.1" "mh-e/mh-acros.el" "mh-e/mh-alias.el" "mh-e/mh-buffers.el" "mh-e/mh-comp.el" "mh-e/mh-compat.el" "mh-e/mh-e.el" "mh-e/mh-folder.el" "mh-e/mh-funcs.el" "mh-e/mh-gnus.el" "mh-e/mh-identity.el" "mh-e/mh-inc.el" "mh-e/mh-junk.el" "mh-e/mh-letter.el" "mh-e/mh-limit.el" "mh-e/mh-mime.el" "mh-e/mh-print.el" "mh-e/mh-scan.el" "mh-e/mh-search.el" "mh-e/mh-seq.el" "mh-e/mh-show.el" "mh-e/mh-speed.el" "mh-e/mh-thread.el" "mh-e/mh-tool-bar.el" "mh-e/mh-utils.el" "mh-e/mh-xface.el")
	(midnight "midnight.el")
	(minibuf-eldef "minibuf-eldef.el")
	(misearch "misearch.el")
	(mixal-mode "progmodes/mixal-mode.el")
	(modula2 "progmodes/modula2.el")
	(morse "play/morse.el")
	(mouse-copy "mouse-copy.el")
	(mouse-drag "mouse-drag.el")
	(mouse-sel "mouse-sel.el")
	(mpc "mpc.el")
	(mpuz "play/mpuz.el")
	(msb "msb.el")
	(mspools "mail/mspools.el")
	(net-utils "net/net-utils.el")
	(netrc "net/netrc.el")
	(network-stream "net/network-stream.el")
	(newsticker "net/newst-backend.el" "net/newst-plainview.el" "net/newst-reader.el" "net/newst-ticker.el" "net/newst-treeview.el" "net/newsticker.el")
	(notifications "notifications.el")
	(novice "novice.el")
	(nroff-mode "textmodes/nroff-mode.el")
	(ntlm "net/ntlm.el")
	(nxml "nxml/nxml-enc.el" "nxml/nxml-glyph.el" "nxml/nxml-maint.el" "nxml/nxml-mode.el" "nxml/nxml-ns.el" "nxml/nxml-outln.el" "nxml/nxml-parse.el" "nxml/nxml-rap.el" "nxml/nxml-uchnm.el" "nxml/nxml-util.el" "nxml/rng-cmpct.el" "nxml/rng-dt.el" "nxml/rng-loc.el" "nxml/rng-maint.el" "nxml/rng-match.el" "nxml/rng-nxml.el" "nxml/rng-parse.el" "nxml/rng-pttrn.el" "nxml/rng-uri.el" "nxml/rng-util.el" "nxml/rng-valid.el" "nxml/rng-xsd.el" "nxml/xmltok.el" "nxml/xsd-regexp.el")
	(octave-mod "progmodes/octave-inf.el" "progmodes/octave-mod.el")
	(org "org/ChangeLog" "org/ob-C.el" "org/ob-R.el" "org/ob-asymptote.el" "org/ob-awk.el" "org/ob-calc.el" "org/ob-clojure.el" "org/ob-comint.el" "org/ob-css.el" "org/ob-ditaa.el" "org/ob-dot.el" "org/ob-emacs-lisp.el" "org/ob-eval.el" "org/ob-exp.el" "org/ob-gnuplot.el" "org/ob-haskell.el" "org/ob-java.el" "org/ob-js.el" "org/ob-keys.el" "org/ob-latex.el" "org/ob-ledger.el" "org/ob-lilypond.el" "org/ob-lisp.el" "org/ob-lob.el" "org/ob-matlab.el" "org/ob-maxima.el" "org/ob-mscgen.el" "org/ob-ocaml.el" "org/ob-octave.el" "org/ob-org.el" "org/ob-perl.el" "org/ob-plantuml.el" "org/ob-python.el" "org/ob-ref.el" "org/ob-ruby.el" "org/ob-sass.el" "org/ob-scheme.el" "org/ob-screen.el" "org/ob-sh.el" "org/ob-sql.el" "org/ob-sqlite.el" "org/ob-table.el" "org/ob-tangle.el" "org/ob.el" "org/org-agenda.el" "org/org-archive.el" "org/org-ascii.el" "org/org-attach.el" "org/org-bbdb.el" "org/org-beamer.el" "org/org-bibtex.el" "org/org-capture.el" "org/org-clock.el" "org/org-colview.el" "org/org-compat.el" "org/org-crypt.el" "org/org-ctags.el" "org/org-datetree.el" "org/org-docbook.el" "org/org-docview.el" "org/org-entities.el" "org/org-exp-blocks.el" "org/org-exp.el" "org/org-faces.el" "org/org-feed.el" "org/org-footnote.el" "org/org-freemind.el" "org/org-gnus.el" "org/org-habit.el" "org/org-html.el" "org/org-icalendar.el" "org/org-id.el" "org/org-indent.el" "org/org-info.el" "org/org-inlinetask.el" "org/org-install.el" "org/org-irc.el" "org/org-jsinfo.el" "org/org-latex.el" "org/org-list.el" "org/org-mac-message.el" "org/org-macs.el" "org/org-mew.el" "org/org-mhe.el" "org/org-mks.el" "org/org-mobile.el" "org/org-mouse.el" "org/org-pcomplete.el" "org/org-plot.el" "org/org-protocol.el" "org/org-publish.el" "org/org-remember.el" "org/org-rmail.el" "org/org-special-blocks.el" "org/org-src.el" "org/org-table.el" "org/org-taskjuggler.el" "org/org-timer.el" "org/org-vm.el" "org/org-w3m.el" "org/org-wl.el" "org/org-xoxo.el" "org/org.el")
	(outline "outline.el")
	(package "emacs-lisp/package-x.el" "emacs-lisp/package.el")
	(page-ext "textmodes/page-ext.el")
	(paren "paren.el")
	(parse-time "calendar/parse-time.el")
	(pascal "progmodes/pascal.el")
	(password-cache "password-cache.el")
	(patcomp "patcomp.el")
	(pcase "emacs-lisp/pcase.el")
	(pcomplete "pcmpl-cvs.el" "pcmpl-gnu.el" "pcmpl-linux.el" "pcmpl-rpm.el" "pcmpl-unix.el" "pcomplete.el")
	(pcvs "vc/pcvs-defs.el" "vc/pcvs-info.el" "vc/pcvs-parse.el" "vc/pcvs-util.el" "vc/pcvs.el")
	(perl-mode "progmodes/perl-mode.el")
	(picture "textmodes/picture.el")
	(po "textmodes/po.el")
	(pong "play/pong.el")
	(pp "emacs-lisp/pp.el")
	(printing "printing.el")
	(proced "proced.el")
	(prolog "progmodes/prolog.el")
	(ps-mode "progmodes/ps-mode.el")
	(ps-print "ps-bdf.el" "ps-def.el" "ps-mule.el" "ps-print.el" "ps-samp.el")
	(python "progmodes/python.el")
	(quickurl "net/quickurl.el")
	(rcirc "net/rcirc.el")
	(rcompile "net/rcompile.el")
	(re-builder "emacs-lisp/re-builder.el")
	(recentf "recentf.el")
	(refbib "textmodes/refbib.el")
	(refer "textmodes/refer.el")
	(refill "textmodes/refill.el")
	(reftex "textmodes/reftex-auc.el" "textmodes/reftex-cite.el" "textmodes/reftex-dcr.el" "textmodes/reftex-global.el" "textmodes/reftex-index.el" "textmodes/reftex-parse.el" "textmodes/reftex-ref.el" "textmodes/reftex-sel.el" "textmodes/reftex-toc.el" "textmodes/reftex-vars.el" "textmodes/reftex.el")
	(regexp-opt "emacs-lisp/regexp-opt.el")
	(regi "emacs-lisp/regi.el")
	(remember "textmodes/remember.el")
	(repeat "repeat.el")
	(reporter "mail/reporter.el")
	(reposition "reposition.el")
	(reveal "reveal.el")
	(rfc2368 "mail/rfc2368.el")
	(rfc822 "mail/rfc822.el")
	(ring "emacs-lisp/ring.el")
	(rlogin "net/rlogin.el")
	(rmail "mail/rmail-spam-filter.el" "mail/rmail.el" "mail/rmailedit.el" "mail/rmailkwd.el" "mail/rmailmm.el" "mail/rmailmsc.el" "mail/rmailout.el" "mail/rmailsort.el" "mail/rmailsum.el")
	(rot13 "rot13.el")
	(rst "textmodes/rst.el")
	(ruby-mode "progmodes/ruby-mode.el")
	(ruler-mode "ruler-mode.el")
	(rx "emacs-lisp/rx.el")
	(sasl "net/sasl-cram.el" "net/sasl-digest.el" "net/sasl-ntlm.el" "net/sasl.el")
	(savehist "savehist.el")
	(saveplace "saveplace.el")
	(sb-image "sb-image.el")
	(scheme "progmodes/scheme.el")
	(scroll-all "scroll-all.el")
	(scroll-lock "scroll-lock.el")
	(secrets "net/secrets.el")
	(select "select.el")
	(sendmail "mail/sendmail.el")
	(server "server.el")
	(ses "ses.el")
	(sgml-mode "textmodes/sgml-mode.el")
	(sh-script "progmodes/sh-script.el")
	(shadow "emacs-lisp/shadow.el")
	(shadowfile "shadowfile.el")
	(shell "shell.el")
	(simula "progmodes/simula.el")
	(skeleton "skeleton.el")
	(smerge-mode "vc/smerge-mode.el")
	(smie "emacs-lisp/smie.el")
	(smtpmail "mail/smtpmail.el")
	(snake "play/snake.el")
	(snmp-mode "net/snmp-mode.el")
	(soap-client "net/soap-client.el" "net/soap-inspect.el")
	(socks "net/socks.el")
	(solitaire "play/solitaire.el")
	(sort "sort.el")
	(soundex "soundex.el")
	(speedbar "speedbar.el")
	(spook "play/spook.el")
	(sql "progmodes/sql.el")
	(strokes "strokes.el")
	(studly "play/studly.el")
	(subword "progmodes/subword.el")
	(supercite "mail/supercite.el")
	(syntax "emacs-lisp/syntax.el")
	(t-mouse "t-mouse.el")
	(table "textmodes/table.el")
	(tabulated-list "emacs-lisp/tabulated-list.el")
	(talk "talk.el")
	(tar-mode "tar-mode.el")
	(tcl "progmodes/tcl.el")
	(telnet "net/telnet.el")
	(tempo "tempo.el")
	(term "term.el")
	(terminal "terminal.el")
	(testcover "emacs-lisp/tcover-ses.el" "emacs-lisp/tcover-unsafep.el" "emacs-lisp/testcover.el")
	(tetris "play/tetris.el")
	(tex-mode "textmodes/tex-mode.el")
	(texinfmt "textmodes/texinfmt.el")
	(texinfo "textmodes/texinfo.el")
	(texnfo-upd "textmodes/texnfo-upd.el")
	(thingatpt "thingatpt.el")
	(thumbs "thumbs.el")
	(tildify "textmodes/tildify.el")
	(time "time.el")
	(time-date "calendar/time-date.el")
	(time-stamp "time-stamp.el")
	(timeclock "calendar/timeclock.el")
	(timezone "timezone.el")
	(tls "net/tls.el")
	(tmm "tmm.el")
	(todo-mode "calendar/todo-mode.el")
	(tpu-edt "emulation/tpu-edt.el" "emulation/tpu-extras.el" "emulation/tpu-mapper.el")
	(tq "emacs-lisp/tq.el")
	(trace "emacs-lisp/trace.el")
	(tramp "net/tramp-cache.el" "net/tramp-cmds.el" "net/tramp-compat.el" "net/tramp-ftp.el" "net/tramp-gvfs.el" "net/tramp-gw.el" "net/tramp-sh.el" "net/tramp-smb.el" "net/tramp-uu.el" "net/tramp.el" "net/trampver.el")
	(tree-widget "tree-widget.el")
	(two-column "textmodes/two-column.el")
	(type-break "type-break.el")
	(uce "mail/uce.el")
	(underline "textmodes/underline.el")
	(undigest "mail/undigest.el")
	(unrmail "mail/unrmail.el")
	(unsafep "emacs-lisp/unsafep.el")
	(url "url/ChangeLog" "url/url-about.el" "url/url-auth.el" "url/url-cache.el" "url/url-cid.el" "url/url-cookie.el" "url/url-dav.el" "url/url-dired.el" "url/url-expand.el" "url/url-file.el" "url/url-ftp.el" "url/url-future.el" "url/url-gw.el" "url/url-handlers.el" "url/url-history.el" "url/url-http.el" "url/url-imap.el" "url/url-irc.el" "url/url-ldap.el" "url/url-mailto.el" "url/url-methods.el" "url/url-misc.el" "url/url-news.el" "url/url-nfs.el" "url/url-ns.el" "url/url-parse.el" "url/url-privacy.el" "url/url-proxy.el" "url/url-queue.el" "url/url-util.el" "url/url-vars.el" "url/url.el")
	(userlock "userlock.el")
	(uudecode "mail/uudecode.el")
	(vc "vc/vc-annotate.el" "vc/vc-arch.el" "vc/vc-bzr.el" "vc/vc-cvs.el" "vc/vc-dav.el" "vc/vc-dir.el" "vc/vc-dispatcher.el" "vc/vc-git.el" "vc/vc-hg.el" "vc/vc-hooks.el" "vc/vc-mtn.el" "vc/vc-rcs.el" "vc/vc-sccs.el" "vc/vc-svn.el" "vc/vc.el")
	(vcursor "vcursor.el")
	(vera-mode "progmodes/vera-mode.el")
	(verilog-mode "progmodes/verilog-mode.el")
	(vhdl-mode "progmodes/vhdl-mode.el")
	(vi "emulation/vi.el")
	(view "view.el")
	(vip "emulation/vip.el")
	(viper "emulation/viper-cmd.el" "emulation/viper-ex.el" "emulation/viper-init.el" "emulation/viper-keym.el" "emulation/viper-macs.el" "emulation/viper-mous.el" "emulation/viper-util.el" "emulation/viper.el")
	(vt-control "vt-control.el")
	(vt100-led "vt100-led.el")
	(warnings "emacs-lisp/warnings.el")
	(wdired "wdired.el")
	(webjump "net/webjump.el")
	(which-func "progmodes/which-func.el")
	(whitespace "whitespace.el")
	(windmove "windmove.el")
	(winner "winner.el")
	(woman "woman.el")
	(ws-mode "emulation/ws-mode.el")
	(xesam "net/xesam.el")
	(xml "xml.el")
	(xscheme "progmodes/xscheme.el")
	(xt-mouse "xt-mouse.el")
	(yow "play/yow.el")
	(zeroconf "net/zeroconf.el")
	(zone "play/zone.el")))

(provide 'minmacs-inf)
(setq minmacs-unsorted-files
      'nil)
;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8
;; End:
;;; finder-inf.el ends here
